lcpu-club/loongarch-packages

- libaio/loong.patch
Test case 5.t failed with the last test:
res = write(rwfd, buf, SIZE);
if (res < 0)
res = -errno;
status |= attempt_rw(rwfd, buf, SIZE,  0,  READ, SIZE);
status |= attempt_rw(rwfd, buf, SIZE,  0, WRITE, res);
attempt_rw return OK while the first write return with error.
> addpatch: libaio, ver=0.3.113-3

- linux/config.loong64.diff
- linux/loong.patch
Add the new source to the end to avoid patch failure caused by upstream hash changes
> upgpatch: linux, ver=6.10.5.arch1-1

- firefox/0010-Fix-libyuv-build-with-LSX-LASX.patch
- firefox/0011-Add-missing-loongarch-lsx-code-for-libpng.patch
- firefox/0012-Add-support-for-LoongArch64.patch
- firefox/0013-Enable-WebRTC-for-LoongArch.patch
- firefox/loong.patch
* remove `--disable-elf-hack` (not applicable to loong)
* Disable crashreporter (not applicable to loong)
* Disable PGO to avoid lld error:
* `relocation R_LARCH_B26 out of range: 171621280 is not in [-134217728, 134217727]`
* 0010-Fix-libyuv-build-with-LSX-LASX.patch to support lsx in libyuv
* 0011-Add-missing-loongarch-lsx-code-for-libpng.patch to support lsx in libpng
* 0012-Add-support-for-LoongArch64.patch and 0013-Enable-WebRTC-for-LoongArch.patch for WebRTC support for loong
> addpatch: firefox, ver=129.0.2-1

- xxhash/loong.patch
Disable option `DISPATCH`, which is only avaliable on x86_64
> addpatch: xxhash, ver=0.8.2-1

- libvpx/loong.patch
* Disable lsx and lasx since functions like `vpx_quantize_b_lsx` are not implmented yet
> addpatch: libvpx, ver=1.14.1-1

- protobuf/loong.patch
* Temporarily use PyPI's source package to build python-protobuf instead of using bazel
* since bazel is missing and need openjdk21
> addpatch: protobuf, ver=27.3-2

- notcurses/loong.patch
* Temporarily disable pandoc since it has not been ported to loong
* Also, temporarily disable python binding that requires pandoc
> addpatch: notcurses, ver=3.0.9-5

- jdk21-openjdk/loong.patch
Change upstream to AOSC as loongarch is not officially supported by openjdk upstream.
> addpatch: jdk21-openjdk

- rust/0010-medium-code-model-on-LoongArch.patch
- rust/loong.patch
* Apply patch to avoid `relocation R_LARCH_B26 out of range` when binary is huge
> updpatch: rust, ver=1:1.81.0-1

- devtools/loong.patch
* Remove missing shellcheck from makedepends
* shellcheck depends on missing ghc
> addpatch: devtools, ver=1:1.2.1-1

- gn/loong.patch
* Clang does not support `-fstack-clash-protection` and will fail by `-Werror`
> addpatch: gn, ver=0.2174.b3a0bff4-1

- devtools-loong64/PKGBUILD
* fix: require correct upstream devtools version
* fix: add arch aliases in loong64 (loongarch64 <--> loong64)
> updpkg: devtools-loong64, ver=1.2.1.patch7-4

- obs-studio/loong.patch
* Disable `QSV11` in loong that it doesn't support loong and will fail in header missing
> addpatch: obs-studio, ver=30.2.1-1

- exim/loong.patch
* change `$CARCH` to `$(uname -m)` to find `build-Linux-loongarch64` instead of loong64, so it can find the right dir
> addpatch: exim, ver=4.98-1

- libyuv/loong.patch
* Fixup pkgver change after patch applying
* Disable pkgver() func
> updpatch: libyuv, ver=r2426+464c51a0

- pacman/loong.patch
- pacman/pacman.conf.loong64.diff
* Fix patch rotten
* Use our `pacman-mirrorlist-loong64` for loong64
> apdpatch: pacman, ver=7.0.0.r3.g7736133-1

- pacman-mirrorlist-loong64/PKGBUILD
- pacman-mirrorlist-loong64/mirrorlist-loong64
* Default to use PKU mirror as cache server
> updpkg: pacman-mirrorlist-loong64

- ocaml/loong.patch
* Disable `frame-pointers` that is not supported on loong64
* Make `world` instead of `world.opt` since native compiler is disabled
> addpatch: ocaml, ver=5.2.0-1

- libblockdev/loong.patch
* Add `-Wno-error=unused-parameter` to `CFLAGS` to prevent from reporting an error
> addpatch: libblockdev, ver=3.1.1-2

- yt6801-dkms/PKGBUILD
added PKGBUILD for motorcomm yt6801 network card to make it able to use
> addpkg :yt6801-dkms, ver=1.0.28-3

- budgie-desktop-view/loong.patch
* Cherry-pick upstreamed fix for new meson and gcc
> addpatch: budgie-desktop-view, ver=1.3-2

- budgie-control-center/loong.patch
* Cherry-pick upstreamed fix for new meson and gcc
* Add missing dependency since upstream splited these packages differently
> addpatch: budgie-control-center, ver=1.4.0-1

- rust/loong.patch
* Compile with `-mcmodel=medium` to avoid `relocation R_LARCH_B26 out of range errors`
* when other programs link to the static library.
> updpatch: rust, ver=1:1.81.0-1.1

- gcc/loong.patch
* Fix rotten patch
* Compile with `-mcmodel=medium` to avoid `relocation R_LARCH_B26 out of range`
* when other programs link to the static library.
> updpatch: gcc, ver=14.2.1+r134+gab884fffe3fc-1.2

- codeblocks/add-loong64-support.patch
- codeblocks/loong.patch
* Fix the error of calling trap as risc-v instruction
* Use architecture-independent `std::raise(SIGTRAP)`
> updpatch: codeblocks, ver=20.03-5.1

- gst-plugins-rs/loong.patch
* Temporarily disable plugins that need nix 0.23, which doesn't support loong64
> addpatch: gst-plugins-rs, ver=0.13.1-2

- libretro-yabause/loong.patch
* Disable to use SSE on loong64 platform
* See also [libretro/yabause#308](https://github.com/libretro/yabause/pull/308)
> addpatch: libretro-yabause, ver=3342-2

- typescript/increase-timeout.patch
- typescript/loong.patch
- typescript/remove-typescript.d.ts-baseline-check.patch
* Remove dprint from dependencies
* since dprint itself and its native plugins relies on prebuilt binaries
* Import patches about check and timeout from archriscv
> addpatch: typescript, ver=5.6.2-1

- john/loong.patch
Apply patch from https://github.com/felixonmars/archriscv-packages/blob/master/john/riscv64.patch 
Fix CPU_FALLBACK_BINARY error in listconf.c
> addpatch: john, ver=1.9.0.jumbo1-11

- librustls/loong.patch
Note: x86 archlinux DO NOT need this patch to build successfully. Reason is unclear.
> addpatch: librustls, ver=0.14.0

- linux-firmware/loong.patch
* Disable to package `amd-ucode` since it's invalid in loong64
> updpatch: linux-firmware, ver=20240928.c979a065-1

- telegram-desktop/loong.patch
* Use `mold` to replace `ld.bfd` as the linker to temporarily avoid the bug of
`binutils`
* `fatal error: ld terminated with signal 11 [Segmentation fault], core
dumped`
> addpatch: telegram-desktop, ver=5.6.0-1.1

- simde/loong.patch
- simde/loongarch-float16-use-a-portable-version-to-avoid-compilation-errors.patch
* Backport type convert patch: https://github.com/simd-everywhere/simde/commit/bda3cdf310925b1e88388f0dc800732dcb690e03
* Swicth to clang since gcc will fail with `internal compiler error`
* Backport patch for float16: https://github.com/simd-everywhere/simde/commit/600050dbd79edaca29cc9649ddb9502041111323
> addpatch: simde, ver=0.8.0-1

- fwupd/loong.patch
* Temporarily disable `pandoc` since it's missing
* Disable unsupported plugins
> addpatch: fwupd, ver=1.9.25-1

- cargo-tauri/loong.patch
* Fix inference error on crate `time` caused by an API change in Rust 1.80.0
> addpatch: cargo-tauri, ver=1.5.11-2

- toolbox/loong.patch
* Backport [loong64 support](https://github.com/containers/toolbox/commit/d7bafb82ed9b3814ccaba5788501f429aa154278)
* Temporarily disable shellcheck since it's missing
> addpatch: toolbox, ver=0.0.99.5-2

- strongswan/loong.patch
* Disable `aesni` since it requires x86's sse, etc.
> addpatch: strongswan, ver=5.9.14-1

- trurl/loong.patch
* Disable `test-memory`, which is not for loong64
> addpatch: trurl, ver=0.16-1

- termusic/loong.patch
* `libsixel` is needed to build in loong64
> addpatch: termusic, ver=0.9.1-1

- upx/loong.patch
* Disable self-pack test for loong64
* See also: https://github.com/felixonmars/archriscv-packages/blob/master/upx/riscv64.patch
> addpatch: upx, ver=4.2.4-1

- diffoscope/loong.patch
* Remove `ghc`, `mono`, `fpc` from checkdepends since they're missing
> addpatch: diffoscope, ver=279-1

- firefox-developer-edition/0001-Add-support-for-LoongArch64.patch
- firefox-developer-edition/0003-update-gn_processor.py-to-support-linux-on-loong64.patch
- firefox-developer-edition/0004-Re-generate-libwebrtc-moz.build-files.patch
- firefox-developer-edition/0005-enable-webrtc-for-loongarch64-in-toolkit-moz.configu.patch
- firefox-developer-edition/0006-Fix-libyuv-unified-source-and-LoongArch-SIMD-build.patch
- firefox-developer-edition/0011-Add-missing-loongarch-lsx-code-for-libpng.patch
- firefox-developer-edition/loong.patch
* Import patches from `firefox`
* Remove --disable-elf-hack (not applicable to loong)
* Disable crashreporter (not applicable to loong)
* Fix the support of lsx/lasx in libyuv and libpng
* Fix webrtc
* Generic loong64 support
> addpatch: firefox-developer-edition, ver=132.0b8-1

- rust/LoongArch64-fix-fp16.patch
- rust/loong.patch
* Temporarily disable f16 in loong64 since our llvm doesn't support it
> updpatch: rust, ver=1:1.82.0-1

- criterion/loong.patch
* Apply https://github.com/Snaipe/BoxFort/pull/51 in BoxFort to support loong64
> addpatch: criterion, ver=2.4.2-3

- gf2x/loong.patch
Add patch from https://github.com/felixonmars/archriscv-packages/blob/master/gf2x/riscv64.patch
> addpatch: gf2x, ver=1.3.0-3

- tcpflow/loong.patch
* Backport upstream fix to build with gcc 13 and later
> addpatch: tcpflow, ver=1.6.1-2

- rust/loong.patch
* Temporarily use `/usr/bin/gcc` to build musl target
* to avoid: `unable to find library -lgcc_s`
> updpatch: rust, ver=1:1.82.0-2

- toolbox/loong.patch
* Upstream has released loong64 support
* Only need to temporarily disable `shellcheck` since it's missing
> updpatch: toolbox, ver=0.0.99.6-1

- qt6-webengine/loong.patch
* Upstream switched to internal ffmpeg and caused header missing
* Temporarily add ffmpeg to makedepends could fix it
> updpatch: qt6-webengine, ver=6.8.0-5

- xfsprogs/loong.patch
> rmvpatch: xfsprogs, ver=6.11.0-1

- linux-firmware/loong.patch
* Upstream uses git files to find firmwares
* See also [check_whence.py#L157](https://gitlab.com/kernel-firmware/linux-firmware/-/blob/e1d95775eb3db64ab3740701bf9682e5856aab2e/check_whence.py#L157)
> updpatch: linux-firmware, ver=20241017.22a6c7dc-1

- a2jmidid/loong.patch
* add definition in sigsegv.c to enable loong64 build
* pull request [a2jmidid#28](https://github.com/jackaudio/a2jmidid/pull/28)
> addpatch: a2jmidid, ver=9-5

- lcdproc/loong.patch
* Update config.{sub,guess}
* Disable LTO due to lto-wrapper fails on unreachable x86 inline assembly:
```
In function ‘port_out’,
inlined from ‘t6963_low_dsp_ready’ at t6963_low.c:181:3:
port.h:351:9: error: impossible constraint in ‘asm’
351 |         __asm__ volatile ("outb %0,%1\n"::"a" (val), "d"(port)
|         ^
make[4]: *** [/tmp/cca6TJKK.mk:2: /tmp/ccT5025n.ltrans0.ltrans.o] Error 1
lto-wrapper: fatal error: make returned 2 exit status
```
> addpatch: lcdproc, ver=0.5.9-10

- tflint/loong.patch
* Disable TestIntegration in check (missing loong64 plugin)
* Disable Test_Install in check (missing loong64 release)
> addpatch: tflint, ver=0.53.0-3

- ppsspp/loong.patch
* Switch to gcc to avoid `error: use of undeclared identifier '__builtin___vfprintf_chk'`
> addpatch: ppsspp, ver=1.17.1-1

- systemd/loong.patch
* Backport [commit 85d0aff](https://github.com/systemd/systemd/pull/34911) to fix bpf build in loong64
> updpatch: systemd, ver=256.7-1

- gitsign/loong.patch
* Loong64 doesn't support `-buildmode=pie` without cgo
* There is a dependency disabled cgo so we need to remove `-buildmode=pie`
> addpatch: gitsign, ver=0.8.0-1

- csound/loong.patch
* Fix build with gcc 14
* Add `CFLAGS` instead of backport since upstream has switched to 7 and 6 in EOL
> addpatch: csound, ver=6.18.1-4

- displaycal/loong.patch
* Backport upstream fix to build with gcc 14
> addpatch: displaycal, ver=3.9.12-2

- audacity/loong.patch
* Skip failed test `lib-numeric-formats` since it does not affect the use of the program
> addpatch: audacity, ver=1:3.7.0-2

- libnbd/loong.patch
* Disable ocaml since ocamlc.opt don't support loong64
* Disable rust since `mio::unix` cannot be imported successfully
> addpatch: libnbd, ver=1.20.0-3

- oha/loong.patch
* Add cmake and clang to makedepends
* since `aws-lc-sys` needs to be built from source in loong64 and requires them
> addpatch: oha, ver=1.4.7-1

- potrace/loong.patch
- update_config
* Disable lto due to lto-wrapper fails on unreachable assembly
> addpatch: potrace, ver=1.16-3

- nanobind/loong.patch
* Remove `python-tensorflow` and `python-pytorch` from `checkdepends` since they're missing
> addpatch: nanobind, ver=2.2.0-1

- python-cairocffi/loong.patch
* Disable `python-xcffib` since it's missing (requires haskell packages)
> addpatch: python-cairocffi, ver=1.6.1-2

- python-pyopencl/loong.patch
* Remove missing `intel-compute-runtime` `rocm-opencl-runtime` from `checkdepends`
> addpatch: python-pyopencl, ver=1:2024.2.6-2

- python-tqdm/loong.patch
* Remove `python-keras` from checkdepends since it's missing and depends on `python-tensorflow`
> addpatch: python-tqdm, ver=4.66.6-1

- qt6-webengine/loong.patch
> updpatch: qt6-webengine, ver=6.8.0-7

- gitea/loong.patch
* Do not fail on checks about Rollup build, which don't support loong64
> addpatch: gitea, ver=1.22.3-1

- emscripten/loong.patch
* Using LLVM target `host` has been [accepted by upstream](https://gitlab.archlinux.org/archlinux/packaging/packages/emscripten/-/commit/c26f897ec897adf0e0dfc6f23fe3f4def9a81e27)
> updpatch: emscripten, ver=3.1.71-2

- libre/loong.patch
* Do not fail on tests that doesn't support to run on loong64 (`Invalid argument`)
> addpatch: libre, ver=3.17.0-1

- grpc/loong.patch
* Fix python arch name (`$CARCH` -> `$(uname -m)`)
> addpatch: grpc, ver=1.65.5-5

- distrho-ports/loong.patch
- distrho-ports/use-simde.patch
* Fix build with gcc14
* Use simde
* Bug: `error: conflicting declaration ‘typedef simde__m128i __m128i’`
* Temporarily switch to `SIMDE_NO_NATIVE`
* This actually disables SIMD and need to be restored after simde's update
> addpatch: distrho-ports, ver=2021.03.15-4

- onnxruntime/loong.patch
From [Felix Yan](https://github.com/felixonmars/archriscv-packages/commit/e0bb650954d22acf9627ddf0fbec7bb0df4aa73f):
> onnxruntime_USE_MPI was guarded with onnxruntime_USE_NCCL before, which is no longer the case now. The MPI path depends on AVX instrinsics for fp16, so we have to disable it for now.
> updpatch: onnxruntime, ver=1.19.2-2

- spring/disable-streflop-for-cutils.patch
- spring/loong.patch
- spring/support-loong64-build.patch
- spring/use-simde.patch
* See also: https://github.com/felixonmars/archriscv-packages/tree/e0bb650954d22acf9627ddf0fbec7bb0df4aa73f/spring
* Support loong64
* Add missing header
* Disable streflop: https://springrts.com/mantis/view.php?id=1846
* Remove arch-specific flags: https://springrts.com/mantis/view.php?id=1788
* Use simde to provide SSE intrinsics
* Bug: `error: conflicting declaration ‘typedef simde__m128i __m128i’`
* Temporarily switch to SIMDE_NO_NATIVE
* This actually disables SIMD
> addpatch: spring, ver=106.0-4

- libretro-play/add-loong64-build.patch
- libretro-play/fix-simd-def-abort.patch
- libretro-play/loong.patch
* Add platform flags for loong64
* Provide generic fallback for functions based on their SSE version, using `simde`
* See also https://github.com/felixonmars/archriscv-packages/commit/5e94b207432d6cb6d643c9439aa30a35238e14fd
* Don't abort in SimdDef.h
> addpatch: libretro-play, ver=8333-1

- openucx/loong.patch
* Apply Loong support patch from PR: https://github.com/openucx/ucx/pull/9899/commits/4462aa94599ee6eb56eb1a751867445a779c995e
* Backport https://github.com/openucx/ucx/commit/a86933eb32646381b6c637395ee9756f59ca2a9f since Loong support patch needs this
* Disable cuda
* Remove rdma-core and rocm from makedepends and optdepends since they are not ready
> addpatch: openucx, ver=1.17.0-3

- avidemux/loong.patch
- Add Loongarch support
- Use *dos2unix* to handle that some upstream CRLF code cannot apply patch
- Add *libmp4v2* dependence
> addpatch: avidemux, ver=2.8.1

- directx-shader-compiler/loong.patch
* Apply https://github.com/microsoft/DirectXShaderCompiler/commit/8c6cc722918c4337e48167735aeb022cb141ac15 to add loong64 support
> addpatch: directx-shader-compiler, ver=1.8.2407-1

- vaultwarden/loong.patch
* Generate Rust bindgen for libmysqlclient at build time
* See also: https://github.com/felixonmars/archriscv-packages/pull/4310/commits/38ef6e8baa353bdcb4e634f18a897e75b6390345
> addpatch: vaultwarden, ver=1.32.5-1

- blender/loong.patch
* Apply [commit d18a0cf277](https://projects.blender.org/blender/blender/commit/d18a0cf277e3d7403eb18718b9cb7a6ec036819f) to support loong64
* Fix missing headers by adding `vulkan-headers` to `makedepends`
> updpatch: blender, ver=17:4.3.0-2

- hedgedoc/loong.patch
- Switch to Node.js v20 because Hedgedoc uses Yarn v4.
- Add some makedepends for building native module
- See also: https://github.com/felixonmars/archriscv-packages/commit/8323610be6eda351cd9957994faa7d524d0da201
> addpatch: hedgedoc, ver=1.9.9-2

- wpewebkit/add-lasx-sources-to-CMakeList.txt.patch
- wpewebkit/loong.patch
- wpewebkit/loongarch-simde-use-a-portable-version-to-avoid-comp.patch
* Backport simde's fix to build with clang: https://github.com/simd-everywhere/simde/commit/600050dbd79edaca29cc9649ddb9502041111323
* Add lasx sources to CMakeList.txt
* Upstream: https://github.com/WebKit/WebKit/pull/37190
> addpatch: wpewebkit, ver=2.46.3-1

- webkitgtk-6.0/add-lasx-sources-to-CMakeList.txt.patch
- webkitgtk-6.0/loong.patch
- webkitgtk-6.0/loongarch-simde-use-a-portable-version-to-avoid-comp.patch
* Backport simde's fix to build with clang: https://github.com/simd-everywhere/simde/commit/600050dbd79edaca29cc9649ddb9502041111323
* Add lasx sources to CMakeList.txt
* Upstream: https://github.com/WebKit/WebKit/pull/37190
> addpatch: webkitgtk-6.0, ver=2.46.3-1

- webkit2gtk-4.1/add-lasx-sources-to-CMakeList.txt.patch
- webkit2gtk-4.1/loong.patch
- webkit2gtk-4.1/loongarch-simde-use-a-portable-version-to-avoid-comp.patch
* Backport simde's fix to build with clang: https://github.com/simd-everywhere/simde/commit/600050dbd79edaca29cc9649ddb9502041111323
* Add lasx sources to CMakeList.txt
* Upstream: https://github.com/WebKit/WebKit/pull/37190
> addpatch: webkit2gtk-4.1, ver=2.46.3-1

- juce/juce_platform.patch
- juce/loong.patch
- juce/loong_fix_relax.patch
- Add loongarch64 support in *JUCE platform detect* and `cpu_relax()` *func*
- Use *dos2unix* to solve chaos CRLF to LF , to apply patch
> addpatch: juce, ver=7.0.12-1

- libtpms/loong.patch
* Back port https://github.com/stefanberger/libtpms/commit/048e207b8e526d5dad072d54bb1fd8218047e3dc to fix [-Werror=stringop-overflow=]
> addpatch: libtpms, ver=0.10.0-1

- xorg-server/10-modeset.conf
- xorg-server/loong.patch
- remove outdated patch *10-modeset.conf* to fix external video card issue
`(II) Platform probe for /sys/devices/pci0000:00/0000:00:10.0/0000:07:00.0/drm/card1`
`(EE) open /dev/dri/card0: No such file or directory`
> updpatch: xorg-server, ver=21.1.14-1.1

- compsize/loong.patch
* Apply https://github.com/kilobyte/compsize/pull/54/commits/a471982c82d1917637cce81a084fcd4b02d6e33b to fix build with current btrfs-progs
> addpatch: compsize, ver=1.5-2

- emovix/loong.patch
- update_config
* Two targets can race when make install. Limit make jobs to 1 to mitigate it.
Upstream bug report: https://sourceforge.net/p/movix/bugs/56/ (though it has been ten years after the last update on the upstream side: https://sourceforge.net/p/movix/activity/?page=0&limit=100 )
> addpatch: emovix, ver=0.9.0-9

- premake/loong.patch
Add loongarch64 support for premake. 
Recent [PR](https://github.com/premake/premake-core/pull/2363) has been merged by upstream. 
Waiting for new release.
**NOTE**
Also add riscv patch here. Riscv support (added recently) is also waiting for new release.  My patch can only be directly applied on the basis of the RV fix; otherwise, patch conflicts will occur.
> addpatch: premake, ver=5.0beta3-1

- devtools/loong.patch
* Apply https://gitlab.archlinux.org/archlinux/devtools/-/merge_requests/289 to fix checkpkg
> updpatch: devtools, ver=1:1.3.0-1.1

- premake/loong.patch
Arch package of premake is now using GitHub-generated sources as desicribed in this [issue](https://github.com/premake/premake-core/issues/2365).
Now source code and tarball have the same line endings: LF.
**Remove** unix2dos command from the patch.
> NOTE
> Also add riscv patch here. Riscv support (added recently) is also waiting for new release. My patch can only be directly applied on the basis of the RV fix; otherwise, patch conflicts will occur.
> updpatch: premake, ver=5.0beta3-2

- edk2/loong.patch
* Enable x86 firmware build
* Needed by `qemu-system-x86`
* Sync build config to loongarch
> updpatch: edk2, ver=202411-1

- kio-extras/loong.patch
* Remove ripgrep-all from depends since it's missing
> addpatch: kio-extras, ver=24.12.0-1

- ripgrep-all/loong.patch
* Update rustix to fix build
* Remove pandoc from checkdepnds since it's missing
* Don't abort due to missing pandoc while checking
> addpatch: ripgrep-all, ver=0.10.6-3

- python-numpy/loong.patch
* Apply https://github.com/google/highway/commit/3da38ea275ef23a08e6ac9098637038ab135081f to fix build on loong64
> addpatch: python-numpy, ver=2.2.0-1

- openpgl/loong.patch
* Apply https://github.com/Cryolitia-Forks/openpgl/commit/77074e2ff062a16ad20f071189dac56e6d075d52 to build on loong64
* Use simde to provide x86 intrinsics
* Bug: error: conflicting declaration ‘typedef simde__m128i __m128i’
* Temporarily switch to `SIMDE_NO_NATIVE`
* This actually disables SIMD
> addpatch: openpgl, ver=0.7.0-1

- age-plugin-tkey/loong.patch
* Back port https://github.com/creack/goselect/commit/8eac7f782437d0705be21241336aedf16d44dc8e for `goselect` to build on loong64
> addpatch: age-plugin-tkey, ver=0.0.5-2

- cilium-cli/loong.patch
* Apply https://github.com/cilium/cilium/pull/36753 to add loong64 support
> addpatch: cilium-cli, ver=0.16.21-1

- libvpx/loong.patch
* Re-enable LSX/LASX
* Back port fix for LSX/LASX
* https://chromium.googlesource.com/webm/libvpx/+/a7863b9a2f01e5d22919a51c95cbc4a9c10fbb2c
* https://chromium.googlesource.com/webm/libvpx/+/a604e10afbb2e711e62d8d9ca9c64b368e30b0e2
> updpatch: libvpx, ver=1.15.0-1

- openrct2/loong.patch
* Apply https://github.com/OpenRCT2/OpenRCT2/commit/935dc6815dc396d7f3b7b10b91f03531e7bf6f88 to build on loong64
> addpatch: openrct2, ver=0.4.17-1

- electron32/compiler-rt-adjust-paths-loong64.patch
- electron32/depot_tools-loong64-support.patch
- electron32/electron-add-loong64-support.patch
- electron32/loong.patch
- electron32/makepkg-source-roller.py.diff
* Add loong64 support in `depot_tools`
* Apply this patch in advance since archlinux's `makepkg-source-roller.py` needs it
* Use `esbuild` binary from npm to replace chromium's `src/third_party/devtools-frontend/src/third_party/esbuild`
* Google's fork doesn't support loong64
* Adjust llvm path to build with llvm 18+
* Modify and clean [patch from darkyzhou](https://github.com/darkyzhou/electron-loong64/blob/32.2.7/electron.patch) and then apply it
* Remove changes to electron `DEPS` (file) and `build` (directory)
* Temporarily depends on system's `libyuv`
Ref: https://github.com/darkyzhou/electron-loong64
> addpatch: electron32, ver=32.2.7-1

- chromium/chromium-loong64-support.patch
- chromium/loong.patch
- chromium/loong64-fix-clang-builtins-path.diff
* Add ` -mcmodel=medium` to CFLAGS etc.
* Modify [Chen Jiajie's patch](https://github.com/AOSC-Dev/chromium-loongarch64/blob/chromium-131.0.6778.85-2/chromium/chromium-131.0.6778.85.diff) and apply it
* Remove AOSC-specific pathes
* Fix clang builtin's path
> addpatch: chromium, ver=131.0.6778.204-1

- electron32/compiler-rt-adjust-paths-loong64.patch
- electron32/electron-add-loong64-support.patch
- electron32/loong.patch
* Remove AOSC style path which causes clang to not find the libyuv header
* Remove the workaround that add libyuv to `depends`
* Add out direct fix for clang/BUILD.gn
> updpatch: electron32, ver=32.2.7-1.1

- chromium/compiler-rt-adjust-paths-loong64.patch
- chromium/loong.patch
* Directly apply out compiler-rt fix patch to the original source
* Replace archlinux's with our compiler-rt-adjust-paths-loong64.patch
> updpatch: chromium, ver=131.0.6778.204-1

- vue-language-tools/loong.patch
* Remove @vscode/vsce from project dependencies to avoid installing since it's proprietary and doesn't suppor loong64
> addpatch: vue-language-tools, ver=2.2.0-1

- ocaml-findlib/loong.patch
* Disable ocaml opt since it's not supported and upstream is unwilling to accept in the near future
> addpatch: ocaml-findlib, ver=1.9.8-1

- fwupd/loong.patch
* If the host does not flash the firmware, `VeryBasicTest.test_get_devices` may fail
* Don't exit when this check fails
> updpatch: fwupd, ver=2.0.3-2

- rust/loong.patch
* Arch Linux upstream has added aarch64 target, which doesn't accept `code-model=medium`
* Make sure `code-model=medium` is only used with loongarch64 target
> updpatch: rust, ver=1:1.83.0-2

- rust/loong.patch
* Rust upstream uses the medium code model for loongarch64 by default since 1.83
* So we don't need to set additional
> updpatch: rust, ver=1:1.83.0-2.1

- firefox-developer-edition/0001-Add-support-for-LoongArch64.patch
- firefox-developer-edition/0002-update-skia-generate_mozbuild.py-to-fix-lasx.patch
- firefox-developer-edition/0004-Re-generate-libwebrtc-moz.build-files.patch
- firefox-developer-edition/loong.patch
* Rebase to the new source
* Fix missing source in skia's generate_mozbuild.py and moz.build
* Fix build with python 3.13
> updpatch: firefox-developer-edition, ver=134.0b10-1

- firefox/0002-update-skia-generate_mozbuild.py-to-fix-lasx.patch
- firefox/loong.patch
* Fix missing source in skia's generate_mozbuild.py and moz.build
* by ptrcnull at https://github.com/lcpu-club/loongarch-packages/pull/308#issuecomment-2576472415
> updpatch: firefox, ver=134.0-1

- devtools-loong64/.SRCINFO
- devtools-loong64/PKGBUILD
- devtools-loong64/get-loong64-pkg
* feat/get-loong64-pkg: add an option to skip to update patch set and upstream dbs
> updpkg: devtools-loong64, ver=1.3.1.patch1-1

- ldc/loong.patch
* Workaround for LLVM 19's bug
* LLVM 19's `generic-la64` doesn't have float point support and is therefore ABI incompatible with binary objects on the system
* Use `-mattr=+d` to enable FP
* This will be fixed in LLVM 20
* Otherwise, it will fail with:
```
CMake Error at cmake/Modules/ExtractDMDSystemLinker.cmake:42 (message): Failed to link empty D program using '/usr/bin/ldmd2 -link-defaultlib-shared=false -linker=lld --flto=thin -wi':
warning: the triple-implied ABI is invalid, ignoring and using feature-implied ABI
ld.lld: error: cmakeExtractDMDSystemLinker.lto.cmakeExtractDMDSystemLinker.o: cannot link object files with different ABI from /usr/lib/gcc/loongarch64-unknown-linux-gnu/14.2.1/../../../Scrt1.o
collect2: error: ld returned 1 exit status
Error: /usr/bin/cc failed with …
```
> updpatch: ldc, ver=3:1.40.0-2

- pocl/loong.patch
* No more need to manually set target
* Some checks still fail
> updpatch: pocl, ver=6.0.r322.gf0e12ad-1

- choria-io/loong.patch
* Update go dependencies to build in loong64
* Set `GOARCH` etc. to loong64
* Don't abort while network error
> addpatch: choria-io, ver=0.23.0-1

- devtools-loong64/.SRCINFO
- devtools-loong64/PKGBUILD
- devtools-loong64/get-loong64-pkg
- devtools-loong64/makepkg-loong64.patch
Add `-mcmodel=medium` to default `CFLAGS` and `CXXFLAGS`
> updpatch: devtools-loong64, ver=1.3.1.patch2-1

- pacman/loong.patch
- pacman/makepkg.loong64.diff
* Sync `CFLAGS`
* Add `-mcmodel=medium` to default `CFLAGS` and `CXXFLAGS`
> updpatch: pacman, ver=7.0.0.r6.gc685ae6-1.1

- electron34/chromium-loong64-support.patch
- electron34/compiler-rt-adjust-paths-loong64.patch
- electron34/depot_tools-loong64-support.patch
- electron34/electron_runtime_api_dalagate-add-loong64-support.patch
- electron34/extensions-common-api-runtime.json-add-loong64.patch
- electron34/loong.patch
- electron34/makepkg-source-roller.py.diff
* Modify and apply Chen Jiajie's [Chromium patch](https://github.com/AOSC-Dev/chromium-loongarch64/blob/44f5819e19be06ede4d24550ebbd33384f777145/chromium/chromium-132.0.6834.83.diff)
* Wipe pathes for AOSC-specific path and compiling configs
* Add loong64 support in `depot_tools`
* Apply this patch in advance since archlinux's `makepkg-source-roller.py` needs it
* Use esbuild binary from npm to replace chromium's src/third_party/devtools-frontend/src/third_party/esbuild
* Google's fork doesn't support loong64
* Modify Arch Linux's llvm path patch to support loong64
* Add loong64 support in `electron_runtime_api_delegate.cc`
* Add loong64 support in `extensions/common/api/runtime.json`
* Disable to fetch the PGO file since loong64's PGO file is not provided
* Use a solution similar to …
> addpatch: electron34, ver=34.0.0-3

- electron32/allow-sched_getaffinity-in-seccomp-for-loong64.patch
- electron32/loong.patch
* Allow `sched_getaffinity` in sandbox's `seccomp` to avoid `SIGSEGV` in loong64
> addpatch: electron32, ver=32.3.0-1.1

- chromium/allow-sched_getaffinity-in-seccomp-for-loong64.patch
- chromium/loong.patch
* Allow `sched_getaffinity` in sandbox's `seccomp` to avoid `SIGSEGV` in loong64
* See also: https://github.com/lcpu-club/loongarch-packages/pull/417
> updpatch: chromium, ver=133.0.6943.53-1

- electron34/allow-sched_getaffinity-in-seccomp-for-loong64.patch
- electron34/loong.patch
* Allow `sched_getaffinity` in sandbox's `seccomp` to avoid `SIGSEGV` in loong64
* See also: https://github.com/lcpu-club/loongarch-packages/pull/417
> updpatch: electron34, ver=34.1.0-1

- vaultwarden-web/loong.patch
* Drop unnecessary remove-electron patch and use env var to skip electron download
> updpatch: vaultwarden-web, ver=2025.1.1-1.1

- boost/include-cstdint-in-all-files-using-fix-width-integer-types.patch
- boost/loong.patch
* Back port https://github.com/boostorg/lockfree/pull/109 to fix errors of fix width int types
> addpatch: boost, ver=1.87.0-2.1

- ollama/cpu-non-avx.patch
- ollama/loong.patch
* Avoid automatically using `loongarch64` as GOARCH
* Disable cuda and rocm
* Build with LASX to fix compiler errors in ggml-cpu-quants.c
* Enable CPU target required by archlinux packaging
> addpatch: ollama, ver=0.5.7-1

- ppsspp/loong.patch
* Back port upstream fix for loong64: https://github.com/hrydgard/ppsspp/commit/489db6b92c75d9f16bc4eb3216a3bed7fe8cc34a
> updpatch: ppsspp, ver=1.18.1-3

- ginkgo-hpc/loong.patch
* Disable cuda and rocm
* Disable test to workaround CMake error with misssing test name
> addpatch: ginkgo-hpc, ver=1.9.0-1

- rocm-llvm/loong.patch
* Set `LLVM_TARGETS_TO_BUILD` to LoongArch
* Disable runtime including libunwind to workaround the error:
```
CMake Error at /build/rocm-llvm/src/rocm-llvm/libunwind/src/CMakeLists.txt:102 (message):
Compiler doesn't support generation of unwind tables if exception support
is disabled.  Building libunwind DSO with runtime dependency on C++ ABI
library is not supported.
```
https://gitlab.kitware.com/cmake/cmake/-/issues/24561
> addpatch: rocm-llvm, ver=6.2.4-1

- hsa-rocr/loong.patch
* Switch to clang since our gcc miss `mm_malloc.h` (WHY?)
* Apply https://github.com/loongarch-moe/rocm-loongarch/blob/rocm-6.2.x/stage2/3.rocm-rocr-runtime/rocr-unsupport.patch to build on loong64
> addpatch: hsa-rocr, ver=6.2.1-1

- hip-runtime/loong.patch
* Apply https://github.com/loongarch-moe/rocm-loongarch/blob/rocm-6.2.x/stage2/7.rocm-clr/clr.patch to build on loong64
* Disable cuda
> addpatch: hip-runtime, ver=6.2.4-1

- rocprim/loong.patch
> addpatch: rocprim, ver=6.2.4-1

- hiprt/loong.patch
* Overwrite x86_64 `easy-encryption` prebuilt.
> addpatch: hiprt, ver=2.3.bd75b7c.rc7-2

- rocm-llvm/loong.patch
* Back port llvm19's fix for fp16 of loong to llvm18
> updpatch: rocm-llvm, ver=6.2.4-1.1

- rocfft/loong.patch
> addpatch: rocfft, ver=6.2.4-1

- rocsparse/loong.patch
> addpatch: rocsparse, ver=6.2.4-1

- hipsparse/loong.patch
> addpatch: hipsparse, ver=6.2.4-1

- rocrand/loong.patch
> addpatch: rocrand, ver=6.2.4-1

- hiprand/loong.patch
> addpatch: hiprand, ver=6.2.4-1

- hipcub/loong.patch
> addpatch: hipcub, ver=6.2.4-1

- roctracer/loong.patch
> addpatch: roctracer, ver=6.2.4-1

- hipify-clang/loong.patch
> addpatch: hipify-clang, ver=6.2.4-1

- rccl/loong.patch
* Apply https://raw.githubusercontent.com/loongarch-moe/rocm-loongarch/refs/heads/rocm-6.2.x/stage3/8.rocm-rccl/rccl-loongarch64.patch to fix build on loong64
> addpatch: rccl, ver=6.2.4-1

- hipblaslt/loong.patch
* Add `rust` to `makedepends`
* Some pip package need to be built from source in loong64 so they need rust
> addpatch: hipblaslt, ver=6.2.4-1

- rocm-opencl-runtime/loong.patch
* Apply https://github.com/loongarch-moe/rocm-loongarch/blob/rocm-6.2.x/stage2/7.rocm-clr/clr.patch to build on loong64
> addpatch: rocm-opencl-runtime, ver=6.2.4-1

- rocm-cmake/loong.patch
* rocm-llvm is ready now
* Remove `-fstack-clash-protection` from CFLAGS and CXXFLAGS to avoid Werror in check()
> updpatch: rocm-cmake, ver=6.2.4-1

- openh264/loong.patch
* Disable LTO to workaround check failure:
```
[ RUN      ] SVC_ME_FunTest.SumOf8x8SingleBlock_lsx
test/encoder/EncUT_SVC_me.cpp:143: Failure
Expected equality of these values:
iRes[0]
Which is: 8276
iRes[1]
Which is: 7586
[  FAILED  ] SVC_ME_FunTest.SumOf8x8SingleBlock_lsx (0 ms)
```
> addpatch: openh264, ver=2.6.0-1

- rocm-llvm/loong.patch
- rocm-llvm/rocm-llvm-fix-fp16.patch
* Use another FP16 fix
* Revert path-related changes
> updpatch: rocm-llvm, ver=6.2.4-1.2

- composable-kernel/loong.patch
* Switch to mold to avoid lld's error
> addpatch: composable-kernel, ver=6.2.4-1

- miopen-hip/loong.patch
* Back port upstream fix for missing RocMLIRPasses.h.inc
* Switch to mold to avoid lld's error
> addpatch: miopen-hip, ver=6.2.4-1

- rocm-llvm/loong.patch
* Re-enable static libs (libunwind, libc++{,abi}) to enable amdclang
* The previous build process of libs actually failed with lld
* Bug: objects generated by compilers in rocm-llvm cannot be linked by lld (neither system's nor rocm-llvm's)
* Switch to mold to workaround the bug above
* Multiple linker specifications are not duplicates
* Some process will append `-fuse-ld=lld` to cover our flag
* We need to set all `LDFLAGS="${LDFLAGS} -fuse-ld=mold"`, `-DCMAKE_LINKER_TYPE=MOLD`, etc.
* Switch the default linker of rocm-llvm to mold to workaround the bug above
* Make rocm-llvm depends on mold
* With above changes, we can remove lots of rocm packages' patch to switch to mold
> updpatch: rocm-llvm, ver=6.2.4-1.3

- vamp-aubio-plugins/build-on-non-x86.patch
- vamp-aubio-plugins/loong.patch
* Enable to build on non-x86 platforms
* See https://github.com/felixonmars/archriscv-packages/commit/36821929032eaf16825cd149b151bb1eeadf38eb
> addpatch: vamp-aubio-plugins, ver=0.5.1-6

- python-proton-vpn-local-agent/loong.patch
* See https://github.com/felixonmars/archriscv-packages/commit/b58f2ca27393719902835e0efca13adf09579e93 and https://github.com/aws/aws-lc-rs/issues/476
* Add CMake and clang to makedepends to build its cargo dependencies from source
* Remove `-D_FORTIFY_SOURCE=3` from CFLAGS and CXXFLAGS to fix assertion in build
> addpatch: python-proton-vpn-local-agent, ver=1.4.3-2

- pycharm-community-edition/loong.patch
* Build natives from source
* Need `cargo` and `go`
* Make use of https://github.com/Glavo/JetBrains-IDE-Multiarch
* Jbr has not been ready yet so we shouldn't install it
* Switch to jdk 21 to workaround error:
``` Could not resolve all dependencies for configuration ':buildSrc:buildScriptClasspath'.
> Could not resolve project :buildSrc.
Required by:
project :buildSrc
> Dependency requires at least JVM runtime version 21. This build uses a Java 17 JVM.
```
> addpatch: pycharm-community-edition, ver=2024.3.3-1

- linux-zen/loong.patch
- linux-zen/rust-gcc-loong64.patch
* Fix to build with gcc when enabling rust in kernel on loong64
> updpatch: linux-zen, ver=6.13.5.zen1-1

- openh264/loong.patch
* Re-enable LTO
* Switch to clang to workaround the bug of gcc: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=119084
* Remove redundant parameters  which are incompatible with `VAACalcSad` in `VAACalcSad_lsx`
> updpatch: openh264, ver=2.6.0-1.1

- gcc/0001-LoongArch-Fix-incorrect-reorder-of-__lsx_vldx-and-__.patch
- gcc/loong.patch
* Back port fix for `__builtin_lsx_vldx`: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=119084
> updpatch: gcc, ver=14.2.1+r753+g1cd744a6828f-1.1

- hipify-clang/loong.patch
* Remove unnecessary setting to use mold since it's moved into rocm-llvm
> updpatch: hipify-clang, ver=6.3.2-1

- rustup/loong.patch
* Add clang and cmake to makedepends until aws-lc-rs' pregenerated riscv64 binding is ready
* See https://github.com/felixonmars/archriscv-packages/commit/f472a0d300a374ffc4b06b1c2d4d2b88785d8903
> addpatch: rustup, ver=1.28.1-1

- chromium/chromium-loong64-support.patch
- chromium/loong.patch
* Fix swiftshader's llvm16
* Rebase to current chromium-*-lite.tar.xz source
> updpatch: chromium, ver=134.0.6998.35-2

- rccl/loong.patch
* Apply https://github.com/loongarch-moe/rocm-loongarch/blob/6.3.1a3/stage4/6.rocm-rccl/rccl-loongarch64.patch to build on loong64
> updpatch: rccl, ver=6.3.2-1

- cargo-msrv/loong.patch
* Extra makedepends to build aws-lc-sys without pre-generated binding
* See also: https://github.com/felixonmars/archriscv-packages/commit/b644118e2dd9475f8f4e70c978cf62554b1b7a99
> addpatch: cargo-msrv, ver=0.18.3-1

- gcc/LoongArch-Support-Q-suffix-for-__float128.patch
- gcc/loong.patch
* Back port patch to support Q suffix for fp128 literal
* See: https://gcc.gnu.org/pipermail/gcc-patches/2025-March/678874.html
> updpatch: gcc, ver=14.2.1+r753+g1cd744a6828f-1.2

- apt-swarm/loong.patch
* Add clang and cmake to makedepends to build aws-lc-sys since there is no prebuilt files for loong64
> addpatch: apt-swarm, ver=0.5.1-1

- chromium/chromium-loong64-support.patch
- chromium/loong.patch
* Rebase to chromium 135
* No more need the extra patch for swiftshader's llvm
> updpatch: chromium, ver=135.0.7049.52-1

- pkgfile/loong.patch
* Handle loongarch64 architecture correctly in updater
* May not be accepted by upstream yet
> addpatch: pkgfile, ver=24-1.1

- arti/loong.patch
* Add cmake and clang to makedepends to build aws-lc-sys
* Switch to mold to workaround segmentation fault of bfd
> addpatch: arti, ver=1.4.2-1

- gstreamer/loong.patch
* Temporarily disable dots-viewer
* dots-viewer now requires nix 0.23.2 to build, but nix 0.23.2 is too old to build on loong64
> updpatch: gstreamer, ver=1.26.0-3

- aichat/loong.patch
* Temporarily switch to wszqkzqk's fork of hnsw_rs
* Replace the hnsw_rs's dependency mmap-rs to memmap2 to fix build
* See: https://github.com/jean-pierreBoth/hnswlib-rs/pull/23/commits/41d206273ee291b6e24ceca21db4aa427b573178
> addpatch: aichat, ver=0.29.0-1

- amdvlk/loong.patch
* Back port https://github.com/nothings/stb/pull/1610/commits/1c4e2d0965103801f735a3f98bccb48b68c5ed2c to build on loong64
* Add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 temporarily, see https://github.com/GPUOpen-Drivers/AMDVLK/issues/402
> addpatch: amdvlk, ver=2025.Q1.3-1

- onnxruntime/fix-loongarch-qgemm.h.patch
- onnxruntime/loong.patch
* Disable cuda since it's property and doesn't support loong64
* Re-enable rocm
* Re-enable *-opt packages with LASX support like Arch Linux upstream's AVX2
* Use another sed command to find system nsync for loong64
* Fallback to default kernel to workaround missing GemmU8U8Dispatch and GemmS8U8Dispatch in LSX
> updpatch: onnxruntime, ver=1.20.2-7

- runc/loong.patch
- runc/runc-update-libseccomp-golang-to-support-loong64.patch
* Add loong64 defs
* Update libseccomp-golang to support loong64
> addpatch: runc, ver=1.2.6-1.1

- java-openjdk/loong.patch
* Switch to loongson's source tree: https://github.com/loongson/jdk
* Adapt the version control to loongson's
* It's impossible for us to follow the upstream version control now
> addpatch: java-openjdk, ver=24.0.ls.27.0-1

- baidupcs-go/loong.patch
* Update `sys` to v0.26.0 to fix build in loong64
> addpatch: baidupcs-go, ver=3.9.7-1

- rust/Filter-out-LoongArch-features-not-supported-by-the-current-LLVM-version.patch
- rust/loong.patch
* Back port https://github.com/rust-lang/rust/commit/a2b3f11700821d778d4dfbc3651a61a0f0f6f3be to fix to work with llvm19
> updpatch: rust, ver=1.87.0-1.1

- composable-kernel/loong.patch
* llvm19 has fp16 support on loong64 so some of the patches are not needed
* Remain the patch to change code model
> updpatch: composable-kernel, ver=6.4.0-1

- calibre/loong.patch
* Skip test for 7z
```
======================================================================  
ERROR: test_7z (calibre.test_build.BuildTest.test_7z)  
----------------------------------------------------------------------  
Traceback (most recent call last):  
File "/build/calibre/src/calibre-8.4.0/src/calibre/test_build.py", line 468, in test_7z  
test_basic()  
~~~~~~~~~~^^  
File "/build/calibre/src/calibre-8.4.0/src/calibre/utils/seven_zip.py", line 93, in test_basic  
do_test()  
~~~~~~~^^  
File "/build/calibre/src/calibre-8.4.0/src/calibre/utils/seven_zip.py", line 82, in do_test    
read_data = {name:af.read() for name, af in zf.readall().items()}  
^^^^^^^^^^  
AttributeError: 'SevenZipFile' object has no attribute 'readall' …
```
> updpatch: calibre, ver=8.4.0-2

- zigbee2mqtt/loong.patch
* Add python to makedepends to fix build
```
npm error code 1
npm error path /build/zigbee2mqtt/src/zigbee2mqtt/node_modules/@serialport/bindings-cpp
npm error command failed
npm error command sh -c node-gyp-build
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@11.2.0
npm error gyp info using node@23.11.1 | linux | loong64
npm error gyp ERR! find Python 
npm error gyp ERR! find Python Python is not set from command line or npm configuration
npm error gyp ERR! find Python Python is not set from environment variable PYTHON
npm error gyp ERR! find Python checking if "python3" can be used
npm error gyp ERR! find Python - executable path is ""
npm error gyp ERR! find Python - "" could not be run
npm error gyp ERR! find Python checking if "python" can be used …
```
> addpatch: zigbee2mqtt, ver=2.4.0-1

- blender/add-loong64-support.patch
- blender/loong.patch
* Store the patch in our repo instead of download it from the link since run curl to get the link will probably get a http page
> updpatch: blender, ver=17:4.4.3-3

- python-matplotlib/loong.patch
* Don't abandon on test failures
* LoongArch's rendering library implementations (such as rounding) seem to differ from other architectures causing tests to fail
> updpatch: python-matplotlib, ver=3.10.3-1

- dust/loong.patch
* Add patch to allow build continuation on LoongArch64 despite test failures
* The architecture uses a 16 KiB default page size which conflicts with tests hardcoded for 4 KiB pages
* This change prevents build failures by allowing test errors while providing explanatory output
> addpatch: dust, ver=1.2.1-1

- python-pillow-avif-plugin/loong.patch
* Back port my fix for incompatible pointer types
> addpatch: python-pillow-avif-plugin, ver=1.5.2-1

- python-datasets/loong.patch
* Add patch to continue build on test failures with a warning
* Network issues of huggingface may cause intermittent test failures
> addpatch: python-datasets, ver=3.6.0-1

- code/loong.patch
* Disable to fetch vsce-sign since it's unavailable on loong64
> updpatch: code, ver=1.100.3-1

- valgrind/loong.patch
* Switch to git repo to support LSX/LASX debug
> updpatch: valgrind, ver=3.25.1-1

- ocaml/loong.patch
* Backport loongarch's machine code support
* Many packages can only work with machine code support
* Upstream link: https://github.com/ocaml/ocaml/pull/11974/commits
* Related issue: https://gitlab.com/nbdkit/libnbd/-/issues/10
> updpatch: ocaml, ver=5.3.0-1.1

- libguestfs/loong.patch
* qemu-related checks will get stuck, so skip the check() process
> addpatch: libguestfs, ver=1.56.0-1

- xwayland-satellite/loong.patch
* Skip wayland_then_x11_clipboard_owner test that cannot run in the systemd-nspawn container
* It's unknown why x86 doesn't have this error
> addpatch: xwayland-satellite, ver=0.6-1

- mesa/loong.patch
* Extra `-D llvm=enabled` is no more needed
> updpatch: mesa, ver=1:25.1.5-1.2

- intel-gmmlib/loong.patch
* Add LoongArch64 build support patch from https://github.com/intel/gmmlib/pull/133/commits
* Add simde as a makedepend
* Set SIMDE_NO_NATIVE flag in CFLAGS/CXXFLAGS to avoid `error: conflicting declaration ‘typedef simde__m128i __m128i’`
> addpatch: intel-gmmlib, ver=22.7.2-1

- intel-media-driver/loong.patch
* Add LoongArch64 build support patch from https://github.com/intel/media-driver/pull/1936/files
* Add simde as a makedepend
* Set SIMDE_NO_NATIVE flag in CFLAGS/CXXFLAGS to avoid `error: conflicting declaration ‘typedef simde__m128i __m128i’`
> addpatch: intel-media-driver, ver=25.2.5-1

- buildbot/loong.patch
- buildbot/yarn.diff
Backport many yarn.lock files to support newer version of rollup to support native compilation. This patch may be removed in next version.
> addpatch: buildbot, ver=4.2.1-2

- markuplinkchecker/loong.patch
* Skip tests that are not suitable for our network environment
```
assertion failed: duration < Duration::from_millis(THROTTLED_TIME_MS)
```
> addpatch: markuplinkchecker, ver=0.22.0-1

- pixi/loong.patch
- pixi/rattler_conda_types-loong64.patch
- pixi/rattler_virtual_packages-loong64.patch
* Backport loong64 support in rattler: https://github.com/conda/rattler/commit/e9152cd1a9941087ca0d500f0212f4da6757694b
* Backport loong64 support in pixi: https://github.com/prefix-dev/pixi/commit/ffbb32a1f3b7396893eceeef244d77ca46419fc9
* Add our trampoline binary
> addpatch: pixi, ver=0.49.0-1

- onetbb/loong.patch
* Backport upstream fix for non-x86 arches
> addpatch: onetbb, ver=2022.2.0-1

- devtools-loong64/.SRCINFO
- devtools-loong64/PKGBUILD
- devtools-loong64/fortran-loong64.patch
* feat: sync with upstream 1.4.0 and add proper fortran support for loong64
* Add and apply fortran-loong64.patch with appropriate FFLAGS for LoongArch64
> updpkg: devtools-loong64, ver=1.4.0.patch1-2

- chromium/loong.patch
* Upstream switched to manual clone but we have to build from tarball
* Get the hash of the tarball from a command
* See also https://gitlab.archlinux.org/archlinux/packaging/packages/chromium/-/merge_requests/11
> updpatch: chromium, ver=138.0.7204.183-1

- nodejs/loong.patch
* Skip failed tests that are almost safe to ignore
* DO NOT ignore the tests that may cause major functional failure
> updpatch: nodejs, ver=23.11.1-1.1

- chromium/loong.patch
* We downgraded nodejs to 23 to workaround the crash of nodejs 24, avoiding the need for modifications for dependencies everywhere
* No more need to switch to nodejs-lts-jod
> updpatch: chromium, ver=138.0.7204.183-1.1

- nodejs-lts-jod/loong.patch
* Skip failed tests that are almost safe to ignore
> updpatch: nodejs-lts-jod, ver=22.18.0-1

- fsverity-utils/loong.patch
* Remove pandoc from makedepneds since it's missing
* fsverity-utils is required by ostree so we need to build it now even without doc
> addpatch: fsverity-utils, ver=1.6-1

- electron37/allow-sched_getaffinity-in-seccomp-for-loong64.patch
- electron37/chromium-loong64-support.patch
- electron37/compiler-rt-adjust-paths-loong64.patch
- electron37/depot_tools-loong64-support.patch
- electron37/electron_runtime_api_dalagate-add-loongarch64-support.patch
- electron37/loong.patch
* Rebase to electron37/chromium138
* Switch to `std:string`'s comparing styles in `electron_runtime_api_delegate.cc` to fix build
* Disable xnnapck on loong64
> addpatch: electron37, ver=37.2.6-1

- binutils/loong.patch
* Backport ths fix for symbol size after relaxation
> updpatch: binutils, ver=2.45+r8+g09be88bfb653-1.1

- pixi/loong.patch
* Upstream has release full support of loong64
* Only handle failed tests since there is no prebuilt python site-package for loong64
> updpatch: pixi, ver=0.52.0-1

- linux-zen/loong.patch
* Apply out-of-tree fix for RDNA4
> updpatch: linux-zen, ver=6.16.4.zen1-1

- patch-check.sh
* check PKGBUILD existence when loong.patch is missing
* run `makepkg --verifysource` to validate sources early
* avoid skipping packages that may require source integrity check
> feat: enhance patch-check.sh for source verification

- vehicle-command/loong.patch
* Update github.com/cronokirby/saferith to build on loong64
> addpatch: vehicle-command, ver=0.3.4-1

- arduino-cli/loong.patch
* Update github.com/creack/goselect to v0.1.3 to build on loong64
> addpatch: arduino-cli, ver=1.2.2-1

- molecule/loong.patch
* Skip test_molecule_schema
* There is a dependency chain:
* test_molecule_schema -> check-jsonschema -> regress -> maturin (cannot build on loong64)
> addpatch: molecule, ver=25.7.0-1

- mesa/loong.patch
* Backport my MR https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/37388 to enable intel vulkan rt on loong64
* Backport my MR https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/37389 to make intel vulkan work on 16 KiB page size
> updpatch: mesa, ver=1:25.2.2-2.1

- docker/loong.patch
- docker/moby-add-support-for-loong64-seccomp.patch
* Add seccomp support for LoongArch64 in moby
* Backport https://github.com/moby/moby/pull/45302
> updpatch: docker, ver=1:28.5.0-1.1
