libsasl/0005-Fix-time-check.patch, libsasl/loong.patch
0005-Fix-time-check.patch is pulled from debian's repo
=> addpatch: libsasl, ver=2.1.28-4

base-devel/loong.patch
add `archlinux-lcpu-keyring` to depends
=> addpatch: base-devel, ver=1-1

libavif/loong.patch
Temporarily do not build documentation for compilation in loong
=> addpatch: libavif, ver=1.1.1-1

ffmpeg/loong.patch
* Disable the hardware support that unavaliable in loong
=> addpatch: ffmpeg, ver=2:7.0.2-1

ffmpeg4.4/loong.patch
* Disable the hardware support that unavaliable in loong
=> addpatch: ffmpeg4.4, ver=4.4.4-6

thunderbird/0100-Add-support-for-LoongArch.patch, thunderbird/0101-Bug-1837935-loong64-Fix-scratch-register-usage-when-.patch, thunderbird/0102-Fix-libyuv-build-with-LSX-LASX.patch, thunderbird/loong.patch
* fix rust nix binding
* fix libyuv's lsx
* fix scratch register usage
=> addpatch: thunderbird, ver=115.14.0-1

gimp/loong.patch
* Add cflag `-Wno-incompatible-pointer-types` to avoid error by incompatible pointer type
* Update config.guess and config.sub
=> addpatch: gimp, ver=2.10.38-1

imlib2/loong.patch
* Remove option `--enable-amd64` which is unavailable in loong
=> addpatch: imlib2, ver=1.12.3-1

qt6-quick3dphysics/0001-physx-loong64.patch, qt6-quick3dphysics/loong.patch
=> addpatch: qt6-quick3dphysics, ver=6.7.2-1

imagemagick/loong.patch
* Remove dep libultrahdr which doesn't support loong
=> addpatch: imagemagick, ver=7.1.1.38-1

openmotif/add_option_main.patch, openmotif/fix_not_literal_format.patch, openmotif/loong.patch
=> addpatch: openmotif, ver=2.3.8-1

opencv/loong.patch
* Remove cuda deps that have not been supported in loong
* Remove gcc13 deps that is only used for cuda
=> addpatch: opencv, ver=4.10.0-4

mplayer/add_loong64_support.patch, mplayer/loong.patch
=> addpatch: mplayer, ver=38542-2

libyuv/0102-Fix-libyuv-build-with-LSX-LASX.patch, libyuv/loong.patch
* fix libyuv build with LSX & LASX
=> addpatch: libyuv, ver=r2426+464c51a03-1

firefox/loong.patch
* Follow upstream to enable LTO and PGO
=> updpatch: firefox, ver=130.0-1

devtools/loong.patch
* Move loong specificity configs to devtools-loong
=> updpatch: devtools, ver=1:1.2.1-1

snapshot/loong.patch
* Extend the test time to avoid timeout
=> addpatch: snapshot, ver=46.3-1

libreoffice-fresh/0001-firebird-la64-support.patch, libreoffice-fresh/0002-UnpackedTarball_firebird.mk-apply-la64-support.diff, libreoffice-fresh/loong.patch
* Enable loong64 support in external/firebird
=> addpatch: libreoffice-fresh, ver=24.8.0-3

libreoffice-still/0001-firebird-la64-support.patch, libreoffice-still/0002-UnpackedTarball_firebird.mk-apply-la64-support.diff, libreoffice-still/loong.patch
* Enable loong64 support in external/firebird
=> addpatch: libreoffice-still, ver=24.2.6-2

qt6-webengine/0001-fix-libyuv-unified-source-and-LoongArch-SIMD-build.patch, qt6-webengine/0006-LOONGARCH64-qtwebengine-chromium-skip-unreliable-ter.patch, qt6-webengine/0007-LOONGARCH64-qtwebengine-chromium-add-LoongArch-suppo.patch, qt6-webengine/loong.patch
* Fix libyuv's lsx/lasx
* Port patches for loong from aosc
=> addpatch: qt6-webengine, ver=6.7.2-2 

qt6-doc/0007-LOONGARCH64-qtwebengine-chromium-add-LoongArch-suppo.patch, qt6-doc/loong.patch
* Add LoongArch support in qtwebengine
=> addpatch: qt6-doc, ver=6.7.2-1

pacman-mirrorlist-loong64/PKGBUILD, pacman-mirrorlist-loong64/mirrorlist-loong64
* Provide mirrorlist needed by loongarchlinux
=> addpkg: pacman-mirrorlist-loong64

paccat/loong.patch
=> addpatch: paccat, ver=1.3.0-1

pyalpm/loong.patch
* Python path use `loongarch64` here instead of `loong64`
=> addpatch: pyalpm, ver=0.10.10-1

gstreamer/loong.patch
Disable onnxruntime and svt-hevc, which don't support loong
=> addpatch: gstreamer, ver=1.24.7-1

glad/loong.patch
=> addpatch: glad, ver=2.0.6-3

yt-dlp/loong.patch
* Temporarily disable pandoc since it's missing
=> addpatch: yt-dlp, ver=2024.08.06-1

pacman/loong.patch, pacman/makepkg.loong64.diff
* Set LDFLAGS with the upstream format
=> updpatch: pacman, ver=7.0.0.r3.g7736133-1

00-update-lock.patch, loong.patch
update Cargo.lock to avoid api incompatibility
=> addpatch: typst

unarj/fix-printf-format.patch, unarj/loong.patch
fix printf error, patch from https://github.com/felixonmars/archriscv-packages/
=> addpatch: unarj

linux-zen/loong.patch
* Removed incorrect disabling of objtool installation
=> updpatch: linux-zen, ver=6.10.10.zen1-1.1

qt5-scripts/0004-LoongArchLinux-QtScript-Add-LoongArch-support.patch, qt5-scripts/loong.patch
=> addpatch: qt5-scripts, ver=5.15.17-3

pacman-mirrorlist-loong64/PKGBUILD, pacman-mirrorlist-loong64/mirrorlist-loong64
* Default to PKU mirror for both db and pkg
=> updpkg: pacman-mirrorlist-loong64, ver=20240920

geeqie/loong.patch
* Temporarily disable pandoc-cli and shellcheck since they're missing
=> addpatch: geeqie, ver=2.4-2

choose/loong.patch
=> addpatch: choose, ver=1.3.4-2

ffmpeg/loong.patch
=> updpatch: ffmpeg, ver=2:7.0.2-3

gstreamer/loong.patch
=> updpatch: gstreamer, ver=1.24.8-1

libreoffice-still/loong.patch
=> updpatch: libreoffice-still, ver=24.2.6-5

onednn/loong.patch
=> addpatch: onednn, ver=3.4.1-1

onnxruntime/loong.patch
* Disable unsupported hardwares
=> addpatch: onnxruntime, ver=1.18.0-3

gstreamer/loong.patch
=> updpatch: gstreamer, ver=1.24.8-1.1

containerd/loong.patch
* Update some go dependencies to build on loong64
=> addpatch: containerd, ver=1.7.22-1

qt6-doc/loong.patch
=> updpatch: qt6-doc, ver=6.7.3-1

git-bug/loong.patch
=> addpatch: git-bug, ver=0.8.0-2

docker/loong.patch
* -buildmode=pie requires external (cgo) linking
=> addpatch: docker, ver=1:24.0.7-1

codeblocks/add-loong64-support.patch, codeblocks/loong.patch
* Add defs for loong64
* Add `--with-boost-libdir=/usr/lib` to set boost's dir
* Update config.guess and config.sub
=> addpatch: codeblocks, ver=20.03-5

geeqie/loong.patch
=> updpatch: geeqie, ver=2.5-1

diskus/loong.patch
* Update `Cargo.lock`
* See also [PR#55 of diskus](https://github.com/sharkdp/diskus/pull/55)
=> addpatch: diskus, ver=0.7.0-4

ghidra/add-loongarch64-build.patch, ghidra/loong.patch
=> addpatch: ghidra, ver=11.0.3-1

jujutsu/loong.patch
Skip the only failed test test_describe_command::test_describe
=> addpatch: jujutsu, ver=0.21.0.1

python-pyfuse3/loong.patch
Change PYTHONPATH to import modules in test files correctly
=> addpatch: python-pyfuse3, ver=3.4.0-1

pika-backup/loong.patch
=> addpatch: pika-backup, ver=0.7.4-1

lorem/loong.patch
=> addpatch: lorem, ver=1.4.2

freecad/loong.patch
* Remove ospray from makedepends since it's missing
=> addpatch: freecad, ver=1.0rc2-2

xmms2/loong.patch
* Fix the lib path to install
* set to `/usr/lib` instead of `/usr/lib64`
* (the latter one is just a symlink to the former one)
=> addpatch: xmms2, ver=0.9.3-5

qemu/loong.patch
* Temporarily disable to pack `qemu-vmsr-helper`
* Otherwise it with fail in package process:
* `mv: cannot stat 'usr/bin/qemu-vmsr-helper': No such file or directory`
=> addpatch: qemu, ver=9.1.0-2

aubio/loong.patch
=> addpatch: aubio, ver=0.4.9-19

pixman/loong.patch
=> updpatch: pixman, ver=0.43.4-1.1

openxr/add-loong64-support.patch, openxr/loong.patch
* Temporary fix from [OpenXR-SDK-Source#479](https://github.com/KhronosGroup/OpenXR-SDK-Source/pull/479)
=> addpatch: openxr, ver=1.0.28-1

openlibm/loong.patch
[PR here](https://github.com/JuliaMath/openlibm/pull/308)
=> addpatch: openlibm, ver=0.8.3

hplip/Prevent-linking-ImageProcessor.patch, hplip/loong.patch
* Import patch from archriscv
* Don't link unused ImageProcessor library because --disable-imageProcessor-build
=> addpatch: hplip, ver=1:3.24.4-2

torsocks/loong.patch
=> addpatch: torsocks, ver=2.4.0-1

libultrahdr/loong.patch
=> addpatch: libultrahdr, ver=1.2.0-1

stlink/loong.patch
* Backport upstreamed patch to fix build with gcc 14
=> addpatch: stlink, ver=1.8.0-1

gimagereader/loong.patch
* Backport upstream fix for enchant_get_prefix_dir
=> addpatch: gimagereader, ver=3.4.2-1

svelte-language-server/loong.patch
=> addpatch: svelte-language-server, ver=0.17.2-1

python-pygit2/loong.patch
=> addpatch: python-pygit2, ver=1.16.0-1

primecount/loong.patch
* Disable f128 for missing support and headers
=> addpatch: primecount, ver=7.14-1

artyfx/disable-sse.patch, artyfx/loong.patch
=> addpatch: artyfx, ver=1.3.1-3

box2d/Fix-type-convert-error-for-LSX.patch, box2d/loong.patch, box2d/remove-unsupported-cpu.patch
* Fix extern/simde's build
* Remove unsupported CPU check
=> addpatch: box2d, ver=3.0.0-1

bustle/loong.patch
* Extend timeout limit of check since it's quite slow
=> addpatch: bustle, ver=0.10.0-1

calibre/fix-stbsp__uintptr.patch, calibre/loong.patch
* Fix stbsp__uintptr for loong64
* Skip test_searching
=> addpatch: calibre, ver=7.17.0-2

jellyfin-ffmpeg/loong.patch
* Disable hardware plugins about NVIDIA
=> addpatch: jellyfin-ffmpeg, ver=1:7.0.2p3-1

desmume/loong.patch
* Fix compile with gcc14
* Fix compile on non-arm platform
=> addpatch: desmume, ver=0.9.13-1

samba/loong.patch
* Fix path of ldb
* `ldb.cpython-312-$CARCH-linux-gnu.so` -> `ldb.cpython-312-$(uname -m)-linux-gnu.so`
=> addpatch: samba, ver=2:4.21.1-1

java21-openjdk/loong.patch
=> addpatch: java21-openjdk, ver=21.0.4-u7-1

matrix-synapse/loong.patch
* Fix python path (`$CARCH` -> `$(uname -m)`)
=> addpatch: matrix-synapse, ver=1.116.0-1

systemctl-tui/loong.patch
=> addpatch: systemctl-tui, ver=0.3.8.1

ldc/loong.patch
* Fix bug during linking in check process
* (undefined reference about atomic)
=> addpatch: ldc, ver=3:1.39.0-1

dcd/loong.patch
* Disable gold to fix linking process
=> addpatch: dcd, ver=1:0.15.2-2

dub/loong.patch
=> addpatch: dub, ver=1.38.1-1

meson/loong.patch
=> updpatch: meson, ver=1.5.2-1

pdftricks/loong.patch
=> addpatch: pdftricks, ver=0.4.1-1

git2png/loong.patch
* Update `sys` to v0.26.0 to fix build in loong64
=> addpatch: gif2png, ver=3.0.3-2

webhook/loong.patch
* Update `sys` to v0.26.0 to fix build in loong64
=> addpatch: webhook, ver=2.8.1-2

brook/loong.patch
* Update `sys` and `net` to fix build in loong64
=> addpatch: brook, ver=20221010-2

mp3info/fix-format-not-a-string-literal-and-no-format-arguments.patch, mp3info/loong.patch
* Fix format error in printf function family
=> addpatch: mp3info, ver=0.8.5a-8

llvm/loong.patch
* Backport llvm 19's fix for fp16 of loong
=> addpatch: llvm, ver=18.1.8-4.1

android-tools/boringssl-add-loong64-support.patch, android-tools/loong.patch
* Add loong64's def to boringssl's header
=> addpatch: android-tools, ver=35.0.2-6

wavegain/add-generic-asm.patch, wavegain/fix-io-header.patch, wavegain/fix-werror-format-security.patch, wavegain/loong.patch
* General fix mainly based on https://github.com/felixonmars/archriscv-packages/commit/269546d6be6932ba805e13bb0fe64500a6b28e5a
=> addpatch: wavegain, ver=1.3.1-4

testu01/fix_not_literal_string.patch, testu01/loong.patch
* Fix printf
* Update autoreconf
=> addpatch: testu01, ver=1.2.3-4

gitlab-runner/loong.patch
* Update `cilium/ebpf` to v0.16.0 to build in loong64
=> addpatch: gitlab-runner, ver=17.5.1-1

libultrahdr/loong.patch
* Change to cherry-pick commit that upstream have accepted
=> updpatch: libultrahdr, ver=1.2.0-1

umoci/loong.patch
* Update `sys` to v0.26.0 to fix build
=> addpatch: umoci, ver=0.4.7-3

fricas/loong.patch
* Temporarily switch to clisp since sbcl is missing
=> addpatch: fricas, ver=1.3.11-1

release-cli/loong.patch
* Update `sys` to v0.26.0 to fix build
=> addpatch: release-cli, ver=0.19.0-1

aida-x/disable-vst3.patch, aida-x/loong.patch
disable vst3 and remove aida-x-vst3 from base aida-x because vst3 doesn't support loong64
=> addpatch: aida-x, ver=1.1.0-1

apko/loong.patch
* Disable some checks since there is no loong64 alpine dependency
=> addpatch: apko, ver=0.19.2-1

libsquish/loong.patch
=> addpatch: libsquish, ver=1.15-8

loki/loong.patch
* Disable `TestFileTarget_StopsTailersCleanly_Parallel` test (condition never satisfied)
=> addpatch: loki, ver=3.2.1-1

valgrind/loong.patch
* Use loongson's source to replace upstream's source
* Disable lib32
=> addpatch: valgrind, ver=3.23.0-5

qt6-webengine/loong.patch
=> updpatch: qt6-webengine, ver=6.8.0-7

sfizz/loong.patch
Add loong64 support [commit 261b5f3](https://github.com/NakanoMiku39/sfizz/commit/261b5f3e1a4c3eef145521125088b2bb1567f544)
=> addpatch: sfizz, ver=1.2.3.4

ntk/loong.patch
* Workaround to fix the path of lib
=> addpatch: ntk, ver=1.3.1001-4.1

fabla/loong.patch
=> addpatch: fabla, ver=1.4-2

sorcer/loong.patch
=> addpatch: sorcer, ver=1.1.3-5

adios2/loong.patch
* Apply wwork around from [GTkorvo/dill#50 (comment)](https://github.com/GTkorvo/dill/issues/50#issuecomment-2155263724)
* See also https://github.com/felixonmars/archriscv-packages/commit/ebe707511c3fe3484dcf226cc3a25c47dd0b76a5
=> addpatch: adios2, ver=2.10.1-3

apptainer/loong.patch
* Update `cilium/ebpf` dependency to build in loong64
=> addpatch: apptainer, ver=1.3.4-1

chmlib/add-loong64-support.patch, chmlib/loong.patch, update_config
* Add loong64 defs
* Update config
=> addpatch: chmlib, ver=0.40-8

emscripten/loong.patch
* Add support for LoongArch target
=> addpatch: emscripten, ver=3.1.67-1

ananicy-cpp/loong.patch
* Add missing `vmlinux.h` header
=> addpatch: ananicy-cpp, ver=1.1.1-5

avisynthplus/loong.patch
* Apply https://github.com/AviSynth/AviSynthPlus/pull/411 to fix build in loong64
=> addpatch: avisynthplus, ver=3.7.3-2

binaryen/loong.patch
=> addpatch: binaryen, ver=1:119-1

brltty/loong.patch
* Disable ocamal since ocamlc.opt don't support loong64
=> addpatch: brltty, ver=6.7-1

libx86emu/loong.patch
=> addpatch: libx86emu, ver=3.5-4

cantor/loong.patch
* Disable julia since it's missing
=> addpatch: cantor, ver=24.08.2-2

horst/fix-format-security.patch, horst/loong.patch
=> addpatch: horst, ver=5.1-2

pocl/loong.patch
* Set architecture to `$(uname -m)`
* Disable failed tests
=> addpatch: pocl, ver=6.0-2

aubio/loong.patch
=> updpatch: aubio, ver-0.4.9-20

mixxx/loong.patch
=> addpatch: mixxx, ver=2.4.1-9

digikam/loong.patch
* Backport upstream fix to build with qt 6.8
=> addpatch: digikam, ver=8.4.0-3

gstreamer/loong.patch
* Don’t abandon builds due to test failures
=> updpatch: gstreamer, ver=1.24.9-2

telegram-desktop/loong.patch
=> updpatch: telegram-desktop, ver=5.7.2-2

phoc/loong.patch
* Don’t abort due to test failures
=> addpatch: phoc, ver=0.42.1-1

nodejs/loong.patch
* Don’t abort due to test failures
=> addpatch: nodejs, ver=23.1.0-1

protobuf/loong.patch
* Do not check our additional source's hash which is not fixed
=> updpatch: protobuf, ver=28.3-1

blender/loong.patch
* Disable unsupported hardwares
=> addpatch: blender, ver=17:4.2.2-4

arrow/loong.patch
=> addpatch: arrow, ver=17.0.0-7

libvirt/loong.patch
* Don’t abort due to test failures
=> addpatch: libvirt, ver=1:10.9.0-1

archlinux-lcpu-keyring/PKGBUILD, archlinux-lcpu-keyring/master-keyids
* add NakanoMiku's fingerprint
=> updpkg: archlinux-lcpu-keyring, ver=20240917-1

edk2/60-edk2-loongarch64.json, edk2/loong.patch
* remove ia32, x64 architecture
* remove edk2-ovmf (ia32 and x64 only)
* add loongarch64 architecture
=> addpatch: edk2, ver=202408.01-1

polyml/loong.patch
* Backport upstream support for loongarch64
=> addpatch: polyml , ver=5.9.1-3

libmemcached-awesome/loong.patch
=> addpatch: libmemcached-awesome, ver=1.1.4-3

symengine/loong.patch
=> addpatch: symengine, ver=0.13.0-1

openmotif/loong.patch
=> updpatch: openmotif, ver=2.3.8-4

scrapy/loong.patch
=> addpatch: scrapy, ver=2.11.1-1

strace/loong.patch
* Don’t abort due to test failures
=> addpatch: strace, ver=6.12-1

openmpi/loong.patch
* Renable openucx since it's ready
=> updpatch: openmpi, ver=5.0.5-2.1

libnbd/loong.patch
=> updpatch: libnbd, ver=1.20.3-1

ltrace/loong.patch
- [Add loongarch64 support](https://github.com/YHStar/ltrace-0.7.3-5/commit/ad72dc9aa5e16f2e98f445aa79c847daea983df6.diff)
- [Fix some tests Headers for gcc14](https://github.com/YHStar/ltrace-0.7.3-5/commit/50791c5ac1e9bedaa4b67d55538dddf5b5afa710.diff)
=> addpatch: ltrace, ver=0.7.3-5

archlinux-lcpu-keyring/PKGBUILD, archlinux-lcpu-keyring/master-keyids
=> updpkg: archlinux-lcpu-keyring, ver=20241126-1

geogram/loong.patch
* Apply https://github.com/BrunoLevy/geogram/pull/192 to build on loong64
=> addpatch: geogram, ver=1.9.1-1

bitwarden-cli/loong.patch
* Remove all the electron dependencies and the husky installer
* See also: https://github.com/felixonmars/archriscv-packages/commit/e2d17527d8572e6176a05ae3a9bf06f8979d1eb2
=> addpatch: bitwarden-cli, ver=2024.11.1-1

opencv/loong.patch
* Upstream added python-opencv-cuda package, and we need to disable it
=> updpatch: opencv, ver=4.10.0-15

seaweedfs/loong.patch
* Replace bolt with bbolt@v1.3.7
=> addpatch: seaweedfs, ver=3.80-1

vault/loong.patch
* Update some go dependencies to build on loong64
=> addpatch: vault, ver=1.18.2-1

ali/loong.patch
* Update golang.org/x/sys to v0.26.0
=> addpatch: ali, ver=0.7.5-3

pnpm/add-pnpm-linux-loong64.patch, pnpm/loong.patch
* Add loong64 build
* Refer to: https://github.com/pnpm/pnpm/pull/8779/commits/913af6b2ad6981637060887a4c80dbdd8e1124e1
* But this is not acceptable to upstream now, see: https://github.com/pnpm/pnpm/pull/8779#issuecomment-2487029909
=> addpatch: pnpm, ver=9.14.4-1

pixman/LoongArch-LSX-and-LASX-SIMD-implementation.patch, pixman/loong.patch
=> updpatch: pixman, ver=0.44.2-1

vcsh/loong.patch
* Refresh automake commands before building
=> addpatch: vcsh, ver=2.0.10-1

blender/loong.patch
=> updpatch: blender, ver=17:4.3.0-4

consul/loong.patch
* Fix `GOARCH` settings and go dependencies
=> addpatch: consul, ver=1.20.1-1

devtools-loong64/PKGBUILD, devtools-loong64/makepkg-loong64.patch, devtools-loong64/pacman-extra-loong64.patch, devtools-loong64/pacman-extra-staging-loong64.patch, devtools-loong64/pacman-extra-testing-loong64.patch
* Sync with upstream's 1.3.0 release
=> updpkg: devtools-loong64, ver=1.3.0.patch1-1

devtools-loong64/PKGBUILD, devtools-loong64/makepkg-loong64.patch
* Undo unnecessary changes in patches
=> updpatch: devtools-loong64, ver=1.3.0.patch2-1

cataclysm-dda/loong.patch
=> addpatch: cataclysm-dda, ver=0.H-2

refind/loong.patch
> - Add patch from yetist's commit [62a1c7](https://github.com/loongarch64/RefindPkg/commit/62a1c7429fc51d6496cd59ebf88399b7520a7fd4.diff)
=> addpatch: refind, ver=0.14.2-1.1

cantor/loong.patch
=> updpatch: cantor, ver=24.12.0-1

calibre/loong.patch
=> updpatch: calibre, ver=7.22.0-1

devtools-loong64/.SRCINFO, devtools-loong64/PKGBUILD, devtools-loong64/get-loong64-pkg
* fix git tag to checkout
* replace ':' with '-'
=> updpkg: devtools-loong64, ver=1.3.0.patch4-1

linux-hardened/0001-LOONGARCH-drm-radeon-Call-mmiowb-at-the-end-of-radeon_ring_commit.patch, linux-hardened/0002-LOONGARCH-drm-xe-fix-build-on-non-4K-kernels.patch, linux-hardened/0003-LOONGARCH-from-AOSCOS-more-fixes-for-Xe-on-LoongArch.patch, linux-hardened/loong.patch
=> updpatch: linux-hardened, ver=6.12.6.hardened1-2

cartridge-cli/loong.patch
* Update go-sysconf to v0.3.14
=> addpatch: cartridge-cli, ver=2.12.5-2

tempo/loong.patch
* Update godeltaprof to 0.1.8 to fix build with current go
=> addpatch: tempo, ver=2.5.0-4

code/loong.patch
* Add missing loong64 definition
=> addpatch: code, ver=1.96.0-1

root/loong.patch
* Disable cuda
* Temporarily disable pythia8 since it's missing
* Apply https://github.com/root-project/root/pull/17341 to build on loong64
=> addpatch: root, ver=6.34.02-1

hepmc/loong.patch
* Temporarily disable pythia8 since it's missing
=> addpatch: hepmc, ver=3.2.6-18

root/loong.patch
* Re-enable pythia8 since it's ready
=> updpatch: root, ver=6.34.02-1.1

sccache/loong.patch
=> addpatch: sccache, ver=0.9.0-1

systemd/loong.patch
=> updpatch: systemd, ver=257.2-1

firefox-developer-edition/0004-Re-generate-libwebrtc-moz.build-files.patch, firefox-developer-edition/loong.patch
* Regenerate libwebrtc `moz.build` files
* Command
```bash
./mach python python/mozbuild/mozbuild/gn_processor.py dom/media/webrtc/third_party_build/gn-configs/webrtc.json
```
=> updpatch: firefox-developer-edition, ver=135.0b1-1

llvm18/loong.patch
* Back port llvm 19's fix for fp16 of loong
=> addpatch: llvm18, ver=18.1.8-1

postgresql/loong.patch
=> updpatch: postgresql, ver=17.2-1

linux-tools/loong.patch
=> updpatch: linux-tools, ver=6.12-11

mage/loong.patch
=> addpatch: mage, ver=1.15.0-2

chromium/chromium-loong64-support.patch, chromium/loong.patch
* Rebase patches
* Accept changes from [Chen Jiajie's patch set](https://github.com/AOSC-Dev/chromium-loongarch64/blob/44f5819e19be06ede4d24550ebbd33384f777145/chromium/chromium-132.0.6834.83.diff)
=> updpatch: chromium, ver=132.0.6834.83-1

glibc/loong.patch
=> updpatch: glibc, ver=2.40+r66+g7d4b6bcae91f-1

archinstall/0001-fix-installer-skip-waiting-for-mirror-selection-on-l.patch, archinstall/loong.patch
* Skip waiting for mirror selectrion on loong64
=> addpatch: archinstall, ver=3.0.2-2.1

libreoffice-still/0002-UnpackedTarball_firebird.mk-apply-la64-support.diff, libreoffice-still/loong.patch
=> updpatch: libreoffice-still, ver=24.8.4-1

.github/workflows/patch-check.yml, patch-check.sh
* Based on scripts of https://github.com/felixonmars/archriscv-packages
=> feat: use github workflow to check PR's patch

python-graph-tool/loong.patch
* Add loong64 to 64 bit arches
=> addpatch: python-graph-tool, ver=2.89-1

devtools-loong64/.SRCINFO, devtools-loong64/PKGBUILD, devtools-loong64/get-loong64-pkg
* Improve git clone error handling and set environment variables
=> updpkg: devtools-loong64, ver=1.3.1.patch3-1

rocblas/loong.patch
=> addpatch: rocblas, ver=6.2.4-1

hipfft/loong.patch
=> addpatch: hipfft, ver=6.2.4-1

hipfft/loong.patch
=> updpatch: hipfft, ver=6.2.4-1

rocsolver/loong.patch
=> addpatch: rocsolver, ver=6.2.4-1

hipblas/loong.patch
=> addpatch: hipblas, ver=6.2.4-1

magma/loong.patch
* Switch to mold, see https://github.com/lcpu-club/loongarch-packages/commit/dc1aad189658be6ed900900c3d887f2c9c007952
* Remove magma-cuda
=> addpatch: magma, ver=2.9.0-1

ginkgo-hpc/loong.patch
=> updpatch: ginkgo-hpc, ver=1.9.0-2

python-pyopencl/loong.patch
=> updpatch: python-pyopencl, ver=1:2024.2.6-3.1

js80p/loong.patch
* Follow upstream's change: `$CARCH` -> `$(uname -m)`
=> updpatch: js80p, ver=3.4.0-1

intellij-idea-community-edition/loong.patch
* Build natives from source
* Make use of https://github.com/Glavo/JetBrains-IDE-Multiarch
=> addpatch: intellij-idea-community-edition, ver=4:2024.3.3-1

pnpm/loong.patch
* See also: https://github.com/Cryolitia-Forks/archriscv-packages/commit/4bf96d2252137bb16de53ca483ef279d5810a53c
=> updpatch: pnpm, ver=10.5.2-1

java11-openjdk/loong.patch
=> updpatch: java11-openjdk, ver=11.0.26.4.u4-1

keycloak/loong.patch, keycloak/use-system-node.patch
=> addpatch: keycloak, ver=26.1.2-1

java21-openjdk/loong.patch
=> updpatch: java21-openjdk, ver=21.0.6.u7-1

linux/loong.patch, linux/rust-gcc-loong64.patch
* Fix to build with gcc when enabling rust in kernel on loong64
=> updpatch: linux, ver=6.13.5.arch1-1

bup/loong.patch
=> addpatch: bup, ver=0.33.7-1

ldc/loong.patch
* Back port upstream fix for test
=> updpatch: ldc, ver=3:1.40.0-2.2

openh264/loong.patch
=> updpatch: openh264, ver=2.6.0-1.2

rocm-llvm/loong.patch
=> updpatch: rocm-llvm, ver=6.3.2-1

devtools-loong64/.SRCINFO, devtools-loong64/PKGBUILD
* Following devtools, create /usr/share/devtools/makepkg.conf.d/loong64.conf.d/{fortran.conf,rust.conf}
=> updpkg: devtools-loong64, ver=1.3.2.patch1-1

linux-hardened/0001-LOONGARCH-drm-radeon-Call-mmiowb-at-the-end-of-radeon_ring_commit.patch, linux-hardened/0002-LOONGARCH-drm-xe-fix-build-on-non-4K-kernels.patch, linux-hardened/0003-LOONGARCH-from-AOSCOS-more-fixes-for-Xe-on-LoongArch.patch, linux-hardened/loong.patch, linux-hardened/loongarch-Use-ASM_REACHABLE.patch, linux-hardened/rust-gcc-loong64.patch
* Rebase to 6.13
* Rebase xe's page size fix
* Fix to build with gcc when enabling rust in kernel on loong64
=> updpatch: linux-hardened, ver=6.13.6.hardened1-1

electron34/loong.patch
* Use system's esbuild instead of the version from npm
=> updpatch: electron34, ver=34.3.1-1

linux/0002-LOONGARCH-drm-xe-fix-build-on-non-4K-kernels.patch, linux/loong.patch, linux/loongarch-Use-ASM_REACHABLE.patch
* Rebase xe's page size fix
* Back port the fix for incorrect annotate_reachable()
=> updpatch: linux, ver=6.13.6.arch1-1

linux-zen/0002-LOONGARCH-drm-xe-fix-build-on-non-4K-kernels.patch, linux-zen/loong.patch, linux-zen/loongarch-Use-ASM_REACHABLE.patch
* Rebase xe's page size fix
* Back port the fix for incorrect annotate_reachable()
=> updpatch: linux-zen, ver=6.13.6.zen1-1

miopen-hip/fix-mlir-llvm-ConstantFolding-ConstantFoldFP128-type.patch, miopen-hip/loong.patch
* fix(llvm ConstantFolding): force cast logf128 to resolve FP128 type
=> updpatch: miopen-hip, ver=6.3.2-1

magma/loong.patch
* There is no more need to explicitly use mold
=> updpatch: magma, ver=2.9.0-2

linux-lts/0002-LOONGARCH-drm-xe-fix-build-on-non-4K-kernels.patch, linux-lts/loong.patch
* Rebase patch for xe's page size
=> updpatch: linux-lts, ver=6.12.19-1

update_config
=> updateconfig: remove gimp

elfutils/loong.patch
* Switch to our debuginfod url
=> addpatch: elfutils, ver=0.192-4

python-pytorch/loong.patch, python-pytorch/sleef_loong64.patch
* Add loong64 support in sleef
* Add loong64 support in cpuinfo
* Disable cuda
=> addpatch: python-pytorch, ver=2.6.0-11

mesa/loong.patch
* Make it harder to get rotten
=> updpatch: mesa, ver=1:25.0.2-2

torchvision/loong.patch
=> addpatch: torchvision, ver=0.20.1-5

torchvision/loong.patch
* Make it harder to get rotten
=> updpatch: torchvision, ver=0.20.1-5

luajit/loong.patch
* Fix luajit bug to make LazyVim work happy.
=> updpatch: luajit, ver=2.1.1741730670-1

electron33/devtools-frontend-disable-terser.patch, electron33/loong.patch
* Disable terser in rollup to fix build
=> updpatch: electron33, ver=33.4.8-1

electron35/allow-sched_getaffinity-in-seccomp-for-loong64.patch, electron35/chromium-loong64-support.patch, electron35/compiler-rt-adjust-paths-loong64.patch, electron35/depot_tools-loong64-support.patch, electron35/electron_runtime_api_dalagate-add-loong64-support.patch, electron35/extensions-common-api-runtime.json-add-loong64.patch, electron35/loong.patch, electron35/makepkg-source-roller.py.diff
* Rebase to electron35/chromium134
* Fix llvm16 in swiftshader
=> addpatch: electron35, ver=35.1.4-1

qt6-doc/loong.patch, qt6-doc/qt6-webengine-add-loong64-support.patch
=> updpatch: qt6-doc, ver=6.9.0-1

arti/loong.patch
=> updpatch: arti, ver=1.4.2-1.1

qemu/loong.patch
* Add edk2-loongarch64 to qemu-system-loongarch64's depends (like aarch and x86)
* Change depends of qemu-base to qemu-system-loongarch64 and move qemu-system-x86 to optdepends
=> updpatch: qemu, ver=9.2.3-1.2

cpu-x/Fix-build-for-unsupport-processer.patch, cpu-x/loong.patch
* Back port https://github.com/TheTumultuousUnicornOfDarkness/CPU-X/commit/2cde825ec67c5f7818846e83ffafa882117eed5b
* Rebase to v5.2.0
=> addpatch: cpu-x ver=5.2.0-2

valkey/loong.patch
* Backport https://github.com/valkey-io/valkey/commit/204097dac46730e9eb125c822c1dc2959c6572c5
=> addpatch: valkey, ver=8.0.2-1

maxima/loong.patch
* Remove unsupported sbcl, use ecl only
=> addpatch: maxima, ver=5.47.0-21

chromium/chromium-loong64-support.patch, chromium/loong.patch
* Fix crash with some chrome addons
=> updpatch: chromium, ver=135.0.7049.95-1.1

ldc/loong.patch
Remove patch that had been merged into upstream
=> updpatch: ldc, ver=3:1.40.1-1

chromium/chromium-loong64-support.patch, chromium/loong.patch
=> updpatch: chromium, ver=136.0.7103.113-1

electron36/allow-sched_getaffinity-in-seccomp-for-loong64.patch, electron36/chromium-loong64-support.patch, electron36/compiler-rt-adjust-paths-loong64.patch, electron36/depot_tools-loong64-support.patch, electron36/electron_runtime_api_dalagate-add-loongarch64-support.patch, electron36/loong.patch
* Rebase to electron36/chromium136
* Follow the changes of upstream in chromium: kLoong64 -> kLoongarch64
=> addpatch: electron36, ver=36.2.1-1

linux-tools/fix-perf-in-loong64.patch, linux-tools/loong.patch
* Back port upstream fix for perf: https://lore.kernel.org/loongarch/20250520063009.23504-1-yangtiezhu@loongson.cn/
=> updpatch: linux-tools, ver=6.14-1

hip-runtime/loong.patch
=> updpatch: hip-runtime, ver=6.4.0-1

zig/loong.patch
* Remove lib32 dependency
* Skip check process to avoid stucking
=> addpatch: zig, ver=0.14.0-1

firefox/loong.patch
=> updpatch: firefox, ver=139.0.4-1

archinstall/loong.patch
* The patch for efi target is included upstream
=> updpatch: archinstall, ver=3.0.7-3

task/loong.patch
* Add clang to makedepends to resolve build dependency issue
=> addpatch: task, ver=3.4.1-1

uutils-coreutils/loong.patch
* Allow build to continue with a warning if tests fail
=> addpatch: uutils-coreutils, ver=0.1.0-1

opensubdiv/loong.patch
=> addpatch: opensubdiv, ver=3.6.0-2

blender/Add-__LP64__-to-64-bit-platform-detection.patch, blender/loong.patch
* Enable rocm support
* Back port https://projects.blender.org/blender/blender/pulls/140528 to fix to build with rocm
=> updpatch: blender, ver=17:4.4.3-3.1

linux-firmware/loong.patch
=> updpatch: linux-firmware, ver=20250613.12fe085f-5

mesa/loong.patch
* Enable Intel Graphics support
=> updpatch: mesa, ver=1:25.1.5-1

simde/loong.patch, simde/simde-add-LSX-support-for-sse2-header-file.patch
* Backport https://github.com/simd-everywhere/simde/pull/1236/files
=> updpatch: simde, ver=0.8.2-1.1

intel-media-driver/loong.patch
* Re-enable native SIMD in simde
=> updpatch: intel-media-driver, ver=25.2.5-1.1

devtools-loong64/.SRCINFO, devtools-loong64/PKGBUILD, devtools-loong64/get-loong64-pkg
* feat: add support for fetching patches from pull requests
=> updpkg: devtools-loong64, ver=1.3.2.patch2-1

qemu/loong.patch
=> updpatch: qemu, ver=10.0.2-1

alicloud-vault/loong.patch
* Update golang.org/x/sys to v0.26.0 to fix build
=> updpatch: alicloud-vault, ver=1.3.4-3

linux-zen/loong.patch
=> updpatch: linux-zen, ver=6.15.6.zen1-1.1

linux/loong.patch
=> updpatch: linux, ver=6.15.6.arch1-1.1

pacman-mirrorlist-loong64/PKGBUILD, pacman-mirrorlist-loong64/mirrorlist-loong64
=> updpkg: pacman-mirrorlist-loong64, ver=20250716-1

pacman-mirrorlist-loong64/PKGBUILD, pacman-mirrorlist-loong64/mirrorlist-loong64
=> updpkg: pacman-mirrorlist-loong64, ver=20250718-1

devtools-loong64/.SRCINFO, devtools-loong64/PKGBUILD, devtools-loong64/mirrorlist-loong64
* Add several new mirror servers to mirrorlist-loong64:
- mirrors.wsyu.edu.cn
- mirrors.nju.edu.cn
- mirror.iscas.ac.cn
=> updpkg: devtools-loong64, ver=1.3.2.patch3-1

chromium/chromium-loong64-support.patch, chromium/loong.patch
=> updpatch: chromium, ver=138.0.7204.168-1

onnxruntime/loong.patch
* fixgitlab.patch is included upstream, no more needed
=> updpatch: onnxruntime, ver=1.22.1-1

binutils/loong.patch
=> updpatch: binutils, ver=2.45+r29+g2b2e51a31ec7-1

linux/loong.patch
* Apply out-of-tree fix for RDNA4
=> updpatch: linux, ver=6.16.4.arch1-1

linux-hardened/loong.patch
* Apply out-of-tree fix for RDNA4
=> updpatch: linux-hardened, ver=6.15.11.hardened1-1.1

linux/loong.patch, linux/revert-mark-xe-driver-as-BROKEN-if-kernel-page-size-is-not-4kB.patch
=> updpatch: linux, ver=6.16.7.arch1-1

linux-zen/loong.patch, linux-zen/revert-mark-xe-driver-as-BROKEN-if-kernel-page-size-is-not-4kB.patch
=> updpatch: linux-zen, ver=6.16.7.zen1-1

baidupcs-go/loong.patch
=> updpatch: baidupcs-go, ver=3.9.8-1

chromium/chromium-loong64-support.patch, chromium/loong.patch
=> updpatch: chromium, ver=140.0.7339.127-1

dqlite/loong.patch
* Backport my PR at https://github.com/canonical/dqlite/pull/847/commits/90ef94fa1c48def355100bb7772e7d3ddd23b555 to fix build with LTO
=> addpatch: dqlite, ver=1.18.2-1

pwru/loong.patch
* Set TARGET_GOARCH to loong64
=> addpatch: pwru, ver=1.0.10-1

simdjson/correct-narrowing-conversion-in-lsx-string-parsing.patch, simdjson/loong.patch
* Backport my PR (merged at https://github.com/simdjson/simdjson/commit/b84a4ec2b98002326977c0d25166f96e93fd498c)
* To fix compiler error by correcting narrowing conversion
=> addpatch: simdjson, ver=1:4.0.3-1

gost/loong.patch
* Update the go dependency cpu to v0.1.1 for loong64 support
=> addpatch: gost, ver=2.12.0-1

aegisub/loong.patch, aegisub/use-supported-luajit-fork.patch
* Use the luajit fork to support loong64: https://github.com/yetist/LuaJIT/tree/arch-2.1.1741730670-loong64
=> addpatch: aegisub, ver=3.4.2-4

vtk/loong.patch
=> updpatch: vtk, ver=9.5.2-1.1
